version: "3.8"

services:
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8089:8080
    environment:
      REDIS_PORT: "6379"
      REDIS_HOST: "redis"
      yourName: "Jujhar"
      port: "8080"

  redis:
    image: redis:6.0-alpine
    expose:
      - "6379/tcp"
